{% set name = "multidimio" %}
{% set version = "0.8.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: dced7de9f5c2ff886ec42c47a64efc1b687b73da8ce2fc0b84b4c48f681f8f40

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - poetry-core

  run:
    - python >=3.9,<3.13
    - click >=8.1.7,<9.0.0
    - click-params >=0.5.0,<0.6.0
    - zarr >=2.18.2,<3.0.0
    - dask-core >=2024.8.0
    - tqdm >=4.67.0,<5.0.0
    - psutil >=6.1.0,<7.0.0
    - fsspec >=2024.10.0
    - segy >=0.3.0,<0.4.0
    - rich >=13.9.4,<14.0.0
    - urllib3 >=1.26.18,<2.0.0  # Remove with https://github.com/TGSAI/mdio-python/blob/ec0b3cdd7a33450ad42b57077dd712200b85c159/pyproject.toml#L36

  run_constrained:
    - distributed >=2024.8.0
    - bokeh >=3.4.2,<4.0.0
    - s3fs >=2024.10.0
    - gcsfs >=2024.10.0
    - adlfs >=2024.7.0
    - zfpy >=0.5.5,<2.0.0

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
