{% set name = "multidimio" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 603fe20834397b186660dcd0609b61c1b0385943a5157efb634e12fdaf599bca

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip
    - poetry-core

  run:
    - python >=3.9,<3.12
    - numba >=0.57.1,<1.0.0
    - dask-core >=2023.8.0
    - psutil >=5.9.5,<6.0.0
    - click-params >=0.4.1
    - tqdm >=4.66.1,<5.0.0
    - click >=8.1.7
    - segyio >=1.9.3,<2.0.0
    - zarr >=2.16.1,<3.0.0
    - fsspec >=2023.9.1

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file:
    - LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
