{% set name = "multidimio" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 54d42e97073386708bc0f184cb9eec17ee91d6934358ab026918a0d860df9a85

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - poetry-core

  run:
    - python >=3.9,<3.13
    - click >=8.1.7,<9.0.0
    - click-params >=0.5.0,<0.6.0
    - zarr >=2.16.1,<3.0.0
    - dask-core >=2023.10.0
    - tqdm >=4.66.1,<5.0.0
    - segyio >=1.9.3,<2.0.0
    - numba >=0.59.1,<0.60.0
    - psutil >=5.9.5,<6.0.0
    - fsspec >=2023.9.1
    - rich >=13.7.1,<14.0.0
    - urllib3 >=1.26.18,<2.0.0  # Remove with https://github.com/TGSAI/mdio-python/blob/ec0b3cdd7a33450ad42b57077dd712200b85c159/pyproject.toml#L36

  run_constrained:
    - distributed >=2023.10.0
    - bokeh >=3.2.2,<4.0.0
    - s3fs >=2023.5.0
    - gcsfs >=2023.5.0
    - adlfs >=2023.4.0
    - zfpy >=0.5.5,<0.6.0

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
