{% set name = "multidimio" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 6f464793dabdc2aa98fc008a204d2d3ef59791199a48768d80c6921f09dd7bfa

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - poetry-core

  run:
    - python >=3.8,<3.12
    - numba >=0.55.2,<0.58.0
    - dask-core >=2022.11.0
    - psutil >=5.9.1,<6.0.0
    - click-params >=0.4.0
    - tqdm >=4.64.0,<5.0.0
    - click >=8.1.3
    - segyio >=1.9.3,<2.0.0
    - zarr >=2.12.0,<3.0.0

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file:
    - LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
