{% set name = "multidimio" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 9003cf5af34b140d5e1cf9dc4a0b8449903809a7e0bd645bfcdef00a8ee7988e

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.17,<0.9.0
    - pip
  run:
    - python >={{ python_min }},<3.14
    - click >=8.2.1
    - click-params >=0.5.0
    - dask-core >=2025.9.0
    - fsspec >=2025.9.0
    - pint >=0.25.0
    - psutil >=7.0.0
    - pydantic >=2.11.9
    - rich >=14.1.0
    - segy >=0.5.0
    - tqdm >=4.67.1,<5.0.0
    - universal-pathlib >=0.2.6
    - xarray >=2025.9.0
    - zarr >=3.1.2

  run_constrained:
    - distributed >=2025.9.0
    - bokeh >=3.8.0
    - s3fs >=2025.9.0
    - gcsfs >=2025.9.0
    - adlfs >=2025.8.0
    - zfpy >=1.0.1

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
