{% set name = "multidimio" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 2e6429f0817f87a67d8e822acf9d15438e7c832d8e34245a7aaf24cb3423206b

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.8.17,<0.9.0
    - pip
  run:
    - python >={{ python_min }},<3.14
    - click >=8.3.0
    - click-params >=0.5.0
    - dask-core >=2025.9.1
    - fsspec >=2025.9.0
    - pint >=0.25.0
    - psutil >=7.1.0
    - pydantic >=2.12.0
    - pydantic-settings >=2.6.1
    - rich >=14.1.0
    - segy >=0.5.3
    - tqdm >=4.67.1
    - universal-pathlib >=0.3.3
    - xarray >=2025.10.1
    - zarr >=3.1.3

  run_constrained:
    - distributed >=2025.9.1
    - bokeh >=3.8.0
    - s3fs >=2025.9.0
    - gcsfs >=2025.9.0
    - adlfs >=2025.8.0
    - zfpy >=1.0.1

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
    - BrianMichell
