{% set name = "multidimio" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 90211f3ef9b23688022fadd3b2720d599f19dc4ec4725cbee718c28ffc598c97

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }},<3.14
    - click >=8.1.7,<9.0.0
    - click-params >=0.5.0,<0.6.0
    - dask-core >=2025.7.0
    - fsspec >=2025.9.0
    - pint >=0.25.0,<1.0.0
    - psutil >=7.0.0,<8.0.0
    - pydantic >=2.11.7,<3.0.0
    - rich >=14.1.0,<15.0.0
    - segy >=0.4.2,<0.5.0
    - tqdm >=4.67.1,<5.0.0
    - universal-pathlib >=0.2.6
    - xarray >=2025.9.0
    - zarr >=3.1.2,<4.0.0

  run_constrained:
    - distributed >=2025.9.0
    - bokeh >=3.8.0,<4.0.0
    - s3fs >=2025.9.0
    - gcsfs >=2025.9.0
    - adlfs >=2025.8.0
    - zfpy >=1.0.1,<2.0.0

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
