{% set name = "multidimio" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/multidimio-{{ version }}.tar.gz
  sha256: 67d521e75c58d4da8765c14a6d878eb4dfe27ecfdf0b5d6e44a48a4e43e3d521

build:
  entry_points:
    - mdio = mdio.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core

  run:
    - python >={{ python_min }},<3.14
    - click >=8.1.7,<9.0.0
    - click-params >=0.5.0,<0.6.0
    - zarr >=3.0.6,<4.0.0
    - dask-core >=2024.12.0
    - tqdm >=4.67.0,<5.0.0
    - psutil >=6.1.0,<7.0.0
    - fsspec >=2024.10.0
    - segy >=0.4.0,<0.5.0
    - rich >=13.9.4,<14.0.0

  run_constrained:
    - distributed >=2024.12.0
    - bokeh >=3.4.2,<4.0.0
    - s3fs >=2024.10.0
    - gcsfs >=2024.10.0
    - adlfs >=2024.7.0
    - zfpy >=1.0.1,<2.0.0

test:
  imports:
    - mdio
  commands:
    - pip check
    - mdio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mdio.dev
  summary: Cloud-native, scalable, and user-friendly multi dimensional energy data!
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/TGSAI/mdio-python

extra:
  recipe-maintainers:
    - tasansal
